# Generated by Django 5.1.4 on 2025-04-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_image_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='media',
            name='file',
        ),
        migrations.AddField(
            model_name='media',
            name='file_url',
            field=models.URLField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post'),
        ),
    ]
