# Generated by Django 5.1.5 on 2025-04-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='email',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='payout',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payout_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
