# Generated by Django 5.1.5 on 2025-04-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payout_amount_remove_payout_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payout',
            old_name='payout_id',
            new_name='payout_batch_id',
        ),
    ]
