# Generated by Django 5.1.4 on 2025-03-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='media',
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
