# Generated by Django 5.1.4 on 2025-03-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_remove_message_media_message_media_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='media_url',
            new_name='media',
        ),
    ]
