# Generated by Django 5.1.4 on 2025-03-20 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('notifications', '0003_rename_message_notification_dm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='dm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.message'),
        ),
    ]
