# Generated by Django 5.1.4 on 2025-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_dm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='dm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
