# Generated by Django 5.1.4 on 2025-03-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_dm'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
