# Generated by Django 5.1.4 on 2025-04-03 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_rename_timestamp_friendrequest_created_at'),
        ('notifications', '0006_notification_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='friend_request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='friends.friendrequest'),
        ),
    ]
