# Generated by Django 5.1.4 on 2025-04-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_friend_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='friend_request_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
